const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "Titles, people, genres",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
    play: "Play",
    moreinfo: "More Info",
  },
  sanskrit: {
    search: "अन्वेषण",
    gptSearchPlaceholder: "उपाधिः, जनाः, विधाः",
    name: "नामः",
    signup: "पञ्जीकरणं कुर्वन्तु",
    signin: "प्रवेशः कुर्वन्तु",
    email: "ईमेल अथवा दूरभाषसङ्ख्या",
    password: "समाभाष्",
    newtonetflix: "नेटफ्लिक्स् इत्यत्र नूतनम्?",
    signupnow: "अधुना पञ्जीकरणं कुर्वन्तु",
    alreadyregistered: "पूर्वमेव पञ्जीकृतः वा ?",
    signinnow: "अधुना प्रवेशं कुर्वन्तु",
    signout: "साइन आउट् कुर्वन्तु",
    nowplaying: "इदानीं क्रीडति",
    toprated: "शीर्ष रेटेड",
    popular: "लोकप्रियं",
    upcoming: "आगामी",
    play: "पश्यतु",
    moreinfo: "अधिकः जानकारी",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "शीर्षक, लोग, शैलियाँ",
    name: "नाम",
    signup: "साइन अप करें",
    signin: "दाखिल करें",
    email: "ईमेल या फ़ोन नंबर",
    password: "पासवर्ड",
    newtonetflix: "नेटफ्लिक्स पर नए हैं?",
    signupnow: "अभी साइनअप करें",
    alreadyregistered: "पहले से ही पंजीकृत?",
    signinnow: "अब साइन इन करो",
    signout: "साइन आउट",
    nowplaying: "अभी चल रही है",
    toprated: "टॉप रेटेड",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    play: "देखे",
    moreinfo: "अधिक जानकारी",
  },
  bhojpuri: {
    search: "तलाशी",
    gptSearchPlaceholder: "शीर्षक, लोग, विधा के बारे में बतावल गइल बा",
    name: "नांव",
    signup: "साइन अप करीं",
    signin: "साइन इन करीं",
    email: "ईमेल या फोन नंबर पर भेजल जा सकेला",
    password: "पासवर्ड",
    newtonetflix: "नेटफ्लिक्स में नया बा?",
    signupnow: "अभी साइन अप करीं",
    alreadyregistered: "पहिलहीं से रजिस्ट्रेशन हो गइल बा?",
    signinnow: "अभी साइन इन करीं",
    signout: "साइन आउट करीं",
    nowplaying: "अब खेलल जा रहल बा",
    toprated: "टॉप रेटेड बा",
    popular: "लोकप्रिय",
    upcoming: "आगामी बा",
    play: "देखीं",
    moreinfo: "अउरी जानकारी खातिर देखीं",
  },
  marathi: {
    search: "शोध",
    gptSearchPlaceholder: "शीर्षके, लोक, शैली",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  gujarati: {
    search: "શોધ",
    gptSearchPlaceholder: "શીર્ષકો, લોકો, શૈલીઓ",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  punjabi: {
    search: "ਖੋਜ",
    gptSearchPlaceholder: "ਸਿਰਲੇਖ, ਲੋਕ, ਸ਼ੈਲੀਆਂ",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  tamil: {
    search: "தேடல்",
    gptSearchPlaceholder: "தலைப்புகள், மக்கள், வகைகள்",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  telugu: {
    search: "వెతకండి",
    gptSearchPlaceholder: "శీర్షికలు, వ్యక్తులు, కళా ప్రక్రియలు",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  nepali: {
    search: "खोज",
    gptSearchPlaceholder: "शीर्षकहरू, मानिसहरू, विधाहरू",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "Títulos, personas, géneros",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  french: {
    search: "Recherche",
    gptSearchPlaceholder: "Titres, personnes, genres",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  russian: {
    search: "поиск",
    gptSearchPlaceholder: "Титулы, люди, жанры",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
  },
};

export default lang;