const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "Titles, people, genres",
    name: "Name",
    signup: "Sign Up",
    signin: "Sign In",
    email: "Email or phone number",
    password: "Password",
    newtonetflix: "New to Netflix?",
    signupnow: "Sign up now",
    alreadyregistered: "Already registered?",
    signinnow: "Sign In now",
    signout: "Sign out",
    nowplaying: "Now Playing",
    toprated: "Top Rated",
    popular: "Popular",
    upcoming: "Upcoming",
    play: "Play",
    moreinfo: "More Info",
    results: "Results",
  },
  sanskrit: {
    search: "अन्वेषण",
    gptSearchPlaceholder: "उपाधिः, जनाः, विधाः",
    name: "नामः",
    signup: "पञ्जीकरणं कुर्वन्तु",
    signin: "प्रवेशः कुर्वन्तु",
    email: "ईमेल अथवा दूरभाषसङ्ख्या इति प्रविष्टं कुर्वन्तु",
    password: "समाभाष् इति प्रविष्टं कुर्वन्तु",
    newtonetflix: "नेटफ्लिक्स् इत्यत्र नूतनम्?",
    signupnow: "अधुना पञ्जीकरणं कुर्वन्तु",
    alreadyregistered: "पूर्वमेव पञ्जीकृतः वा ?",
    signinnow: "अधुना प्रवेशं कुर्वन्तु",
    signout: "साइन आउट् कुर्वन्तु",
    nowplaying: "इदानीं क्रीडति",
    toprated: "शीर्ष रेटेड",
    popular: "लोकप्रियं",
    upcoming: "आगामी",
    play: "पश्यतु",
    moreinfo: "अधिकः जानकारी",
    results: "परिणामाः",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "शीर्षक, लोग, शैलियाँ",
    name: "नाम",
    signup: "साइन अप करें",
    signin: "दाखिल करें",
    email: "ईमेल या फ़ोन नंबर दर्ज करें",
    password: "पास वर्ड दर्ज करें",
    newtonetflix: "नेटफ्लिक्स पर नए हैं?",
    signupnow: "अभी साइनअप करें",
    alreadyregistered: "पहले से ही पंजीकृत?",
    signinnow: "अब साइन इन करो",
    signout: "साइन आउट",
    nowplaying: "अभी चल रही है",
    toprated: "टॉप रेटेड",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    play: "देखे",
    moreinfo: "अधिक जानकारी",
    results: "परिणाम",
  },
  bhojpuri: {
    search: "तलाशी",
    gptSearchPlaceholder: "शीर्षक, लोग, विधा के बारे में बतावल गइल बा",
    name: "नांव",
    signup: "साइन अप करीं",
    signin: "साइन इन करीं",
    email: "ईमेल या फोन नंबर दर्ज करीं",
    password: "पासवर्ड दर्ज करीं",
    newtonetflix: "नेटफ्लिक्स में नया बा?",
    signupnow: "अभी साइन अप करीं",
    alreadyregistered: "पहिलहीं से रजिस्ट्रेशन हो गइल बा?",
    signinnow: "अभी साइन इन करीं",
    signout: "साइन आउट करीं",
    nowplaying: "अब खेलल जा रहल बा",
    toprated: "टॉप रेटेड बा",
    popular: "लोकप्रिय बा",
    upcoming: "आगामी बा",
    play: "देखीं",
    moreinfo: "अउरी जानकारी खातिर देखीं",
    results: "परिणाम",
  },
  marathi: {
    search: "शोध",
    gptSearchPlaceholder: "शीर्षके, लोक, शैली",
    name: "नाव",
    signup: "साइन अप करा",
    signin: "साइन इन करा",
    email: "ईमेल किंवा फोन नंबर प्रविष्ट करा",
    password: "पासवर्ड टाका",
    newtonetflix: "नेटफ्लिक्स वर नवीन?",
    signupnow: "आत्ताच नोंदणी करा",
    alreadyregistered: "आधीच नोंदणी झाली आहे?",
    signinnow: "आता साइन इन करा",
    signout: "साइन आउट करा",
    nowplaying: "आता खेळत आहे",
    toprated: "सर्वाधिक मानांकित",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    play: "पहा",
    moreinfo: "अधिक माहिती",
    results: "परिणाम",
  },
  gujarati: {
    search: "શોધ",
    gptSearchPlaceholder: "શીર્ષકો, લોકો, શૈલીઓ",
    name: "નામ",
    signup: "સાઇન અપ કરો",
    signin: "સાઇન ઇન કરો",
    email: "ઇમેઇલ અથવા ફોન નંબર દાખલ કરો",
    password: "પાસવર્ડ દાખલ કરો",
    newtonetflix: "નેટફ્લિક્સ માટે નવા છો?",
    signupnow: "અત્યારે જોડવ",
    alreadyregistered: "પહેલેથી નોંધાયેલ છે?",
    signinnow: "હમણાં સાઇન ઇન કરો",
    signout: "સાઇન આઉટ કરો",
    nowplaying: "હવે રમવાનું",
    toprated: "ઉત્તમ",
    popular: "પ્રખ્યાત",
    upcoming: "આગામી",
    play: "રમ",
    moreinfo: "વધુ માહિતી",
    results: "પરિણામો",
  },
  punjabi: {
    search: "ਖੋਜ",
    gptSearchPlaceholder: "ਸਿਰਲੇਖ, ਲੋਕ, ਸ਼ੈਲੀਆਂ",
    name: "ਨਾਮ",
    signup: "ਸਾਇਨ ਅਪ",
    signin: "ਸਾਈਨ - ਇਨ",
    email: "ਈਮੇਲ ਜਾਂ ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    password: "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
    newtonetflix: "नेटफ्लिक्स ਲਈ ਨਵੇਂ?",
    signupnow: "ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ",
    alreadyregistered: "ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ?",
    signinnow: "ਹੁਣੇ ਸਾਈਨ ਇਨ ਕਰੋ",
    signout: "ਸਾਇਨ ਆਉਟ",
    nowplaying: "ਹੁਣ ਚੱਲ ਰਿਹਾ ਹੈ",
    toprated: "ਚੋਟੀ ਦੇ ਦਰਜਾ",
    popular: "ਪ੍ਰਸਿੱਧ",
    upcoming: "ਆਗਾਮੀ",
    play: "ਖੇਡੋ",
    moreinfo: "ਹੋਰ ਜਾਣਕਾਰੀ",
    results: "ਨਤੀਜੇ",
  },
  tamil: {
    search: "தேடல்",
    gptSearchPlaceholder: "தலைப்புகள், மக்கள், வகைகள்",
    name: "பெயர்",
    signup: "பதிவு செய்யவும்",
    signin: "உள்நுழையவும்",
    email: "மின்னஞ்சல் அல்லது தொலைபேசி எண்",
    password: "கடவுச்சொல்",
    newtonetflix: "Netflix க்கு புதியவரா?",
    signupnow: "இப்பொது பதிவு செய்",
    alreadyregistered: "ஏற்கனவே பதிவு செய்யப்பட்டது?",
    signinnow: "இப்போது உள்நுழையவும்",
    signout: "வெளியேறு",
    nowplaying: "தற்பொழுது விளையாடி கொண்டிருக்கிறேன்",
    toprated: "சிறந்த தரமதிப்பீடு",
    popular: "பிரபலமானது",
    upcoming: "வரவிருக்கிறது",
    play: "விளையாடு",
    moreinfo: "மேலும் தகவல்",
    results: "முடிவுகள்",
  },
  telugu: {
    search: "వెతకండి",
    gptSearchPlaceholder: "శీర్షికలు, వ్యక్తులు, కళా ప్రక్రియలు",
    name: "పేరు",
    signup: "చేరడం",
    signin: "సైన్ ఇన్ చేయండి",
    email: "ఇమెయిల్ లేదా ఫోన్ నంబర్",
    password: "పాస్వర్డ్",
    newtonetflix: "Netflixకి కొత్తవా?",
    signupnow: "ఇప్పుడే సైన్ అప్",
    alreadyregistered: "ముందే నమోదుయాయ్యింది?",
    signinnow: "ఇప్పుడే సైన్ ఇన్ చేయండి",
    signout: "సైన్ అవుట్ చేయండి",
    nowplaying: "ఇప్పుడు ఆడుతున్నారు",
    toprated: "టాప్ రేటింగ్",
    popular: "జనాదరణ పొందినది",
    upcoming: "రాబోయేది",
    play: "ప్లే",
    moreinfo: "మరింత సమాచారం",
    results: "ఫలితాలు",
  },
  nepali: {
    search: "खोज",
    gptSearchPlaceholder: "शीर्षकहरू, मानिसहरू, विधाहरू",
    name: "नाम",
    signup: "साइन अप",
    signin: "साइन इन गर्नुहोस्",
    email: "इमेल वा फोन नम्बर प्रविष्ट गर्नुहोस्",
    password: "पासवर्ड प्रविष्ट गर्नुहोस्",
    newtonetflix: "Netflix मा नयाँ?",
    signupnow: "अहिले साइन अप गर्नुहोस्",
    alreadyregistered: "दर्ता भएको छ?",
    signinnow: "अहिले साइन इन गर्नुहोस्",
    signout: "साइन आउट गर्नुहोस्",
    nowplaying: "अहिले प्ले हुँदैछ",
    toprated: "शीर्ष मूल्याङ्कन",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    play: "खेल्नु",
    moreinfo: "थप जानकारी",
    results: "परिणामहरू",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "Títulos, personas, géneros",
    name: "Nombre",
    signup: "Inscribirse",
    signin: "Iniciar sesión",
    email: "Correo electrónico o número de teléfono",
    password: "Contraseña",
    newtonetflix: "¿Nuevo en Netflix?",
    signupnow: "Regístrate ahora",
    alreadyregistered: "¿Ya registrado?",
    signinnow: "Regístrate",
    signout: "desconectar",
    nowplaying: "Jugando ahora",
    toprated: "Los más valorados",
    popular: "Popular",
    upcoming: "Próximo",
    play: "jugar",
    moreinfo: "Más información",
    results: "Resultados",
  },
  french: {
    search: "Recherche",
    gptSearchPlaceholder: "Titres, personnes, genres",
    name: "Nom",
    signup: "S'inscrire",
    signin: "Se connecter",
    email: "Email ou numéro de téléphone",
    password: "Mot de passe",
    newtonetflix: "Nouveau sur Netflix ?",
    signupnow: "S'inscrire maintenant",
    alreadyregistered: "Déjà enregistré?",
    signinnow: "Connectez vous maintenant",
    signout: "se déconnecter",
    nowplaying: "Lecture en cours",
    toprated: "Les mieux notés",
    popular: "Populaire",
    upcoming: "A venir",
    play: "jouer",
    moreinfo: "Plus d'informations",
    results: "Résultats",
  },
  russian: {
    search: "поиск",
    gptSearchPlaceholder: "Титулы, люди, жанры",
    name: "Имя",
    signup: "Зарегистрироваться",
    signin: "Войти",
    email: "Электронная почта или номер телефона",
    password: "Пароль",
    newtonetflix: "Впервые в Netflix?",
    signupnow: "Войти Сейчас",
    alreadyregistered: "Уже зарегистрирован?",
    signinnow: "Войдите сейчас",
    signout: "выход",
    nowplaying: "Сейчас играет",
    toprated: "Самые популярные",
    popular: "Популярный",
    upcoming: "Предстоящие",
    play: "играть",
    moreinfo: "Больше информации",
    results: "Полученные результаты",
  },
};

export default lang;